title: "Tails IM"
description: "Профиль и резюме Tails IM."
image: "https://cdn-storage.github.io/images/avatars/dun43v.01.png"
lang: "ru_RU"

defaults:
  - scope:
      path: ""
    values:
      image: "https://cdn-storage.github.io/images/avatars/dun43v.01.png"

author:
  name: "Tails IM"
  email: "ru.tails.im@gmail.com"
  github: "Tails-IM"
  twitter: "Tails_IM"

twitter:
  username: "Tails_IM"
  card: summary

social:
  name: "Tails IM"
  links:
    - https://tails.im
    - https://twitter.com/Tails_IM
    - https://linkedin.com/in/Tails_IM
    - https://github.com/Tails-IM
    - https://gitlab.com/Tails-IM

webmaster_verifications:
  google: ""
  yandex: ""

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
